### ISSUE TITLE
duplicate a request, then try to change url of the duplicate and both requests change

### ISSUE THREAD

**Issue by dwolfhub** [luckymarmot/Paw-Issues#24] opened 2015-03-10 03:13 UTC
osx 10.10.2

**Comment by hishnash** [comment] 2015-11-27 10:41
@dwolfhub can you test this again on the latest release 2.2.6 i cant reproduce it

**Comment by mittsh** [comment] 2015-11-27 11:27
@dwolfhub @hishnash I'm very positive that this bug have been fixed a while ago (sorry for the late answer). Closing this issue. @dwolfhub please let us know if this still happens to you...

**Closed by mittsh** 2015-11-27 11:27 UTC
